---
# Title: role-zabbix-server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/main.yml
#
# Description:
#   This task file contains the steps for installing a 
#   Zabbix server via packages and MariaDB server via docker
#   This taskfile depends on 'role-mariadb-docker'.
#
#   Source(s):
#     - https://github.com/bitfinity-nl/role-mariadb-docker/
#   
- name: "Install Zabbix server when operating system is Ubuntu on host '{{ ansible_hostname }}'"
  include_tasks: tasks/zabbix-server-version.yml
  with_items: "{{ zabbix_repository }}"
  when: ansible_distribution == "Ubuntu"

- name: "Install and configure Apache as a reverseproxy on host '{{ ansible_hostname }}'"
  include_tasks: tasks/zabbix-apache-reverseproxy.yml
