---
# Title: role-zabbix-server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/main.yml
#
# Description:
#   Playbook for deploying Zabbix server
#
#- name: "Install Zabbix server version 6 on Ubuntu 24.04LTS (Noble Numbat)"
#  include_tasks: tasks/2404/zabbix-server-6.yml
    
- name: "Install MariaDB docker"
  include_tasks: tasks/zabbix-mariadb-preinstall.yml
  with_items: "{{ zabbix_repository }}"
  when: ansible_distribution == "Ubuntu"    
    
#- name: "Install Zabbix server when operating system is Ubuntu on host '{{ ansible_hostname }}'"
#  include_tasks: tasks/zabbix-server-version.yml
#  with_items: "{{ zabbix_repository }}"
#  when: ansible_distribution == "Ubuntu"

#- name: "Install apache2"
#  include_tasks: tasks/2404/apache2.yml
