---
# Title: role-zabbix-server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/zabbix-mariadb-preinstall.yml
#
# Description:
#   This task file contains the steps for installing 
#   MariaDB server via docker. This taskfile depends on
#   'role-mariadb-docker' 
#
#   Source(s):
#     - https://github.com/bitfinity-nl/role-mariadb-docker/
#
- name: "Set MariaDB version for Zabbix '{{ item.version }}' release"
  ansible.builtin.set_fact:
    mariadb_docker_image_tags: '{{ item.mariadb_docker_version }}'
  when: zabbix_install_version == item.version
    
- name: "Install MariaDB docker"
  ansible.builtin.include_role:
    name: role-mariadb-docker
  when: zabbix_install_version == item.version
