---
# Title: Zabbix server install Ubuntu
#
# Author: bitfinity-nl
# Owner: bitfinity-nl
#
# File: tasks/handlers/main.yml
#
# Description:
#   Taskfile for deploying Zabbix server on Ubuntu.
#  
- name: "mariadb_disable_global_log_bin_trust_function_creators"
  community.mysql.mysql_variables:
    variable: log_bin_trust_function_creators
    value: 1
    login_user: "{{ zabbix_proxy_administrative_user }}"
    login_password: "{{ zabbix_proxy_administrative_pass }}"
  no_log: True

- name: "mariadb_import_database_schema"
  raw: docker exec -it mariadb bash -c 'cat /zabbix_proxy.sql | mariadb --default-character-set=utf8mb4 -uroot -p{{ zabbix_proxy_administrative_pass }} zabbix_proxy'
  no_log: false

- name: "mariadb_enable_global_log_bin_trust_function_creators"
  community.mysql.mysql_variables:
    variable: log_bin_trust_function_creators
    value: 0
    login_user: "{{ zabbix_proxy_administrative_user }}"
    login_password: "{{ zabbix_proxy_administrative_pass }}"
  no_log: True

- name: "systemd_enable_start_zabbix-proxy"
  ansible.builtin.systemd:
    name: "{{ systemd_service }}"
    state: started
    enabled: yes
    masked: no
  loop:
    - zabbix-proxy
  loop_control:
    loop_var: systemd_service

- name: "systemd_restart_zabbix-proxy"
  ansible.builtin.systemd:
    name: zabbix-proxy
    state: restarted


- name: "restart_apache2"
  ansible.builtin.systemd:
    name: apache2
    state: restarted
    enabled: yes
    masked: no

- name: "reload_apache2"
  ansible.builtin.systemd:
    name: apache2
    state: reloaded

